# # This is a basic workflow to help you get started with Actions

name: CI

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

on:
  schedule:
    # If it's been 24 hrs, every 15th minute, Monday through Friday,
    # if it's the weekend and the world is ending, ping a team member if you need something reviewed asap
    # however if the world will end, then the PR probably doesn't matter, maybe don't ping them
    - cron: '*/15 * * * 1-5'

jobs:
  deploy:
    name: Review reminders
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: tommykw/pull-request-reviewee-reminder-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reminder_message: 'This PR has been open for 24+ hours, teamwork makes the dream work!'
          pull_request_lifetime_hours: 24
